NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

# Account Information
ACCOUNTS=[
    "GA6E6QV7SZZS5W2AI7TBXP2FGFYMMP4ZM56ST7KDV52T7GIRHZT5WQ64"
]

# Documentation
[
DOCUMENTATION
]
ORG_NAME="EGT Token"
ORG_URL="https://charlesoxendine.github.io/EGT/"
ORG_DESCRIPTION="EGT Token on the Stellar Network"
ORG_PHYSICAL_ADDRESS="N/A"
ORG_OFFICIAL_EMAIL="N/A"

# Token/Currency Information
[[
CURRENCIES
]]
code="EGT"
issuer="GA6E6QV7SZZS5W2AI7TBXP2FGFYMMP4ZM56ST7KDV52T7GIRHZT5WQ64"
display_decimals=7
name="EGT Token"
desc="EGT Token on the Stellar Network"
conditions="See project documentation for terms and conditions"
is_asset_anchored=false
anchor_asset_type="other"
status="live"
