name: Add CORS headers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create site directory
        run: |
          mkdir -p _site/.well-known
          cp .well-known/stellar.toml _site/.well-known/
          echo "/*" > _site/_headers
          echo "  Access-Control-Allow-Origin: *" >> _site/_headers
          echo "  Access-Control-Allow-Methods: GET" >> _site/_headers
          echo "  Access-Control-Allow-Headers: Content-Type" >> _site/_headers

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
